# Generated by Django 5.0.6 on 2024-05-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.TextField()),
                ('short_url', models.CharField(max_length=128, null=True)),
                ('hit_count', models.IntegerField(default=0)),
            ],
        ),
    ]
